// Entry file ("main" in bothub.json), generated by scripts/create.mjs.
// It joins the layers into the plugin object the BotHub SDK runs:
//   nodes/<name>.js    -> blocks   (definition: nodes/<name>.json)
//   events/<event>.js  -> events   (names: bothub.json "events")
//   services/tasks.js  -> tasks    (schedule: bothub.json "services.tasks")
// commands/ and dashboard/ need no code; the core reads them from bothub.json.
// Adding a node: nodes/<name>.json + nodes/<name>.js, its name in bothub.json "nodes", and a line below.
import hello from './nodes/hello.js';
import replyFor from './nodes/reply_for.js';
import count from './nodes/count.js';
import announce from './nodes/announce.js';
import apiGet from './nodes/api_get.js';
import playSound from './nodes/play_sound.js';
import stopSound from './nodes/stop_sound.js';
import guildMemberAdd from './events/guildMemberAdd.js';
import { tasks } from './services/tasks.js';

/** @type {import('@bothub/sdk').PluginDefinition} */
export default {
  async onEnable(ctx) {
    await ctx.logger.info(`${ctx.plugin.getId()} ${ctx.plugin.getVersion()} enabled for bot ${ctx.botId}`);
  },
  blocks: { hello, reply_for: replyFor, count, announce, api_get: apiGet, play_sound: playSound, stop_sound: stopSound },
  events: { guildMemberAdd },
  tasks,
};
